version: '3'

services:
    landing-page:
        container_name: landing-page
        image: landing-page
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        stdin_open: true
        tty: true
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - .:/usr/src/app
        ports:
          - "3000:3000"